import NodeGraph from '../components/NodeGraph';
import Head from 'next/head'
import styles from '@/styles/Graph.module.css'
import { UserButton } from '@clerk/nextjs'


const HomePage = () => {
    const nodes = [
        { id: 1, label: 'Node 1' },
        { id: 2, label: 'Node 2' },
        { id: 3, label: 'Node 3' },
    ];

    const edges = [
        { from: 1, to: 2 },
        { from: 2, to: 3 },
        { from: 3, to: 1 },
    ];

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <UserButton/>
                <NodeGraph nodes={nodes} edges={edges} />
            </main>
        </>
    );
};

export default HomePage; 