import NodeGraph from '../components/NodeGraph';
import Head from 'next/head';
import styles from '@/styles/Graph.module.css';
import Navbar from '../components/Navbar';
import Button from '../components/Button';
import JournalModal from '../components/JournalModal';
import { useState } from 'react';
import { GraphResponse } from '@/types/GraphType';

type Node = {
  id: number;
  label: string;
};

type Edge = {
  from: number;
  to: number;
};

const Graph = () => {
  let graphResponse:GraphResponse = {
    graph: [{"keyword1": {"keyword2": ["keyword3", "keyword4"]}, "keyword5": {}}],
    frequency: {"keyword1": 3, "keyword2": 1, "keyword3": 5, "keyword4": 1, "keyword5": 1}
  }
  const nodes: Node[] = [
    { id: 1, label: 'User' },
    { id: 2, label: 'People' },
    { id: 3, label: 'Ike' },
    { id: 4, label: 'Tarun' },
    { id: 5, label: 'Food' },
    { id: 6, label: 'Pizza' },
  ];

  const edges: Edge[] = [
    { from: 1, to: 2 },
    { from: 1, to: 5 },
    { from: 2, to: 3 },
    { from: 2, to: 4 },
    { from: 5, to: 6 },
  ];

  const [selectedNodeId, setSelectedNodeId] = useState<number | null>(null);

  const handleNodeDoubleClick = (nodeId: number) => {
    setSelectedNodeId(nodeId);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <h1 className={styles.h1}>Choose a view:</h1>
        <Button />
        <NodeGraph nodes={nodes} edges={edges} onNodeDoubleClick={handleNodeDoubleClick} />
        {selectedNodeId !== null && (
          <JournalModal
            header="Sample Journal Header"
            body="Sample Journal Body"
            onClose={() => setSelectedNodeId(null)}
          />
        )}
      </main>
    </>
  );
};

export default Graph;
