import { useEffect } from 'react';
import Head from 'next/head'
import { DataSet, Network } from 'vis';
import styles from '@/styles/Graph.module.css'

export default function NodeGraph() {
  useEffect(() => {
    const nodes = new DataSet([
      { id: 1, label: 'Node 1' },
      { id: 2, label: 'Node 2' },
      { id: 3, label: 'Node 3' },
      { id: 4, label: 'Node 4' },
      { id: 5, label: 'Node 5' },
    ]);

    const edges = new DataSet([
      { from: 1, to: 2 },
      { from: 1, to: 3 },
      { from: 2, to: 4 },
      { from: 3, to: 4 },
      { from: 4, to: 5 },
    ]);

    const container = document.getElementById('node-graph');

    
    const data = {
      nodes,
      edges,
    };

    const options = {};

    if (container != null) {
        const network = new Network(container, data, options);
    }
    
  }, []);

  return (
    <>
     <Head>        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={styles.main}>
      <div id="node-graph"></div>
    </main>
    </>

  );
}