import Navbar from '../components/Navbar';
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, FormEvent } from 'react';
import { SignOutButton, UserButton, UserProfile, useAuth } from '@clerk/nextjs'
import Datepicker from '../components/Datepicker';
import ValidatorContainer from '@/components/ValidatorContainer';


function JournalEntryForm() {
  const [body, setBody] = useState('');
  const [selectedDate, setSelectedDate] = useState(new Date());

  const handleDateChange = (date: Date) => {
    setSelectedDate(date);
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const response = await fetch('/api/journal-entries', {
      method: 'POST',
      body: JSON.stringify({ body, date: selectedDate.toISOString() }),
    });
    if (response.ok) {
      setBody('');
      setSelectedDate(new Date());
      // Optionally, redirect to a page that shows the newly created journal entry
    }
  };

  return (
    <form onSubmit={handleSubmit} className={styles.form}>
      <div className={styles.inputWrapper}>
        <div>
          <label htmlFor={styles.body}>Date Selected:</label><br />
          <Datepicker onDateChange={handleDateChange} />
        </div>

        <textarea
          id={styles.body}
          value={body}
          onChange={(event) => setBody(event.target.value)}
        ></textarea>
      </div>
      <button type="submit" className={styles.submitButton}>Submit</button>
    </form>
  );
}

export default function Home() {
  const apiCall = async () => {
    let res = await fetch("/api/hello")
    console.log(res)
  }
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  return (
    <>
      <Head>        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />

        <div className={styles.formWrapper}>
          <JournalEntryForm />
          <ValidatorContainer
  initialWords={[
    "apple",
    "banana",
    "cherry",
    "date",
    "elderberry",
    "fig",
    "grape",
    "honeydew",
    "kiwi",
    "lemon",
    "mango",
    "nectarine",
    "orange",
    "pineapple",
    "quince",
    "raspberry",
    "strawberry",
    "tangerine",
    "ugli fruit",
    "watermelon",
  ]}
/>

        </div>
      </main>
    </>
  )
}
