version: "3"
services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    command: mongod --auth
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
  #   ports:
  #     - "9200:9200"
  #   expose:
  #     - "9200"
  #   environment:
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
  #     - discovery.type=single-node
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.9.1
  #   ports:
  #     - "80:5601"
  #   expose:
  #     - "80"
  #   environment:
  #     SERVER_NAME: localhost
  #     ELASTICSEARCH_URL: http://elasticsearch:9200/
