version: "3"
services:
  mongo:
    container_name: CSDS351-mongo
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    command: mongod --auth
